import "@/app/ui/globals.css";
import localFont from "next/font/local";

const proximaNova = localFont({
  src: "../public/fonts/Proxima-Nova-Font.otf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${proximaNova.className} h-screen`}>{children}</body>
    </html>
  );
}
